sudo: required
services:
  - docker

before_install:
  - docker build -t darrellsnow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true darrellsnow/react-test npm test

after_success:
  - docker build -t darrellsnow/multi-client ./client
  - docker build -t darrellsnow/node-complex-nginx ./nginx
  - docker build -t darrellsnow/multi-server ./server
  - docker build -t darrellsnow/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push darrellsnow/multi-client
  - docker push darrellsnow/node-complex-nginx
  - docker push darrellsnow/multi-server
  - docker push darrellsnow/multi-worker


#deploy:
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "node-complex"
#  env: "NodeFrontend-env"
#  bucket_name: "elasticbeanstalk-us-west-2-180405251853"
#  bucket_path: "node-complex"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"